version: '3'


services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    volumes:
       - ./logstash:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - "5601:5601"
    environment:
       - ELASTICSEARCH_USERNAME="elastic"
       - ELASTICSEARCH_PASSWORD="changeme"
       - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    networks:
      - elk


networks: 
  elk:
    external:
      name: portal_net