version: '3'

services:

  client:
    build: 
      context: './vaccination-client/'
      dockerfile: 'Dockerfile'
    env_file:
      - ./.env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}

  config-service:
    build:
      context: './vaccination-services/config-service/'
      dockerfile: Dockerfile
      args:
        PORT: ${CONFIG_PORT}
    env_file:
      - ./.env
    ports:
      - ${CONFIG_PORT}:${CONFIG_PORT}
    networks:
      - portal_net

  discovery-service:
    build:
      context: './vaccination-services/discovery-service/'
      dockerfile: Dockerfile
      args:
        CONFIG_URL: ${CONFIG_URL}
        DISCOVERY_PORT: ${DISCOVERY_PORT}
    env_file:
      - ./.env
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}
    depends_on:
      - config-service
    networks:
      - portal_net

  gateway-service:
    build:
      context: './vaccination-services/gateway-service/'
      dockerfile: Dockerfile
      args:
        CONFIG_URL: ${CONFIG_URL}
        DISCOVERY_URL: ${DISCOVERY_URL}
        GATEWAY_PORT: ${GATEWAY_PORT}
    env_file:
      - ./.env
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - config-service
    networks:
      - portal_net

  user-management-service:
    build:
      context: './vaccination-services/user-management-service/'
      dockerfile: Dockerfile
      args:
        CONFIG_URL: ${CONFIG_URL}
        DISCOVERY_URL: ${DISCOVERY_URL}
        USER_MANAGEMENT_PORT: ${USER_MANAGEMENT_PORT}
    env_file:
      - ./.env
    ports:
      - ${USER_MANAGEMENT_PORT}:${USER_MANAGEMENT_PORT}
    depends_on:
      - config-service
    networks:
      - portal_net

  immunization-portal-service:
    build:
      context: './vaccination-services/immunization-portal-service/'
      dockerfile: Dockerfile
      args:
        CONFIG_URL: ${CONFIG_URL}
        DISCOVERY_URL: ${DISCOVERY_URL}
        USER_MANAGEMENT_PORT: ${IMMUNIZATION_PORTAL_PORT}
    env_file:
      - ./.env
    ports:
      - ${IMMUNIZATION_PORTAL_PORT}:${IMMUNIZATION_PORTAL_PORT}
    depends_on:
      - config-service
    networks:
      - portal_net

  mail-service:
    build:
      context: './vaccination-services/mail-service/'
      dockerfile: Dockerfile
      args:
        CONFIG_URL: ${CONFIG_URL}
        DISCOVERY_URL: ${DISCOVERY_URL}
        USER_MANAGEMENT_PORT: ${MAIL_PORT}
    env_file:
      - ./.env
    ports:
      - ${MAIL_PORT}:${MAIL_PORT}
    depends_on:
      - config-service
    networks:
      - portal_net

networks: 
  portal_net:
    external:
      name: portal_net