server:
  port: ${PORT:8888}
   
spring:
  config:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mijura/vaccination-app-config
          cloneOnStart: true